import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner';
import { CheckCircle, AlertCircle } from "lucide-react"

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Club Care",
  description: "Generated by bluespark",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
          {children}
          <Toaster richColors
          position="top-right"
          icons={{
            success: <CheckCircle className="text-green-600 w-5 h-5" />,
            error: <AlertCircle className="text-red-600 w-5 h-5" />,
          }}
          toastOptions={{
            classNames: {
              success: "bg-green-50 text-green-900",
              error: "bg-red-50 text-red-900",
            }
          }}
        />
      </body>
    </html>
  );
}
